baseURL = "https://ramtin-ehsani.github.io/"
title = "Ramtin Ehsani"
theme = ["hugo-coder", "hugo-cite"]
languageCode = "en"
defaultContentLanguage = "en"
publishDir = "docs"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true

# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
fontheading = "Raleway"
fontbody = "Raleway"
# Changing font here is not enough, also change in _variables.css

author = "Ramtin Ehsani"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Ramtin Ehsani's personal and professional website"
keywords = "academia,sciences,software,SE"
info = ["PhD Candidate"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2020
# license = "CC BY-SA 4.0"
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/partigabor/partigabor.github.io"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme, supported values:
# "auto" (use preference set by browser) "dark" (dark background, light foreground) "light" (light background, dark foreground) (default)
colorScheme = "light"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []
# Favicon
favicon = "/images/favicon.png"
favicon_32 = "/images/favicon-32x32.png"
favicon_16 = "/images/favicon-16x16.png"


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "CV"
icon = "fa fa-2x fa-file-pdf-o"
weight = 1
url = "files/cv.pdf"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/ramtin-ehsani/"

[[params.social]]
name = "Google Scholar"
icon = "ai ai-google-scholar ai-2x"
weight = 2
url = "https://scholar.google.com/citations?user=BLBeIuQAAAAJ&hl=en"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 3
url = "mailto:ramtin.ehsani@drexel.edu"

# [[params.social]]
# name = "Twitter"
# icon = "fa fa-2x fa-twitter"
# weight = 3
# url = "https://twitter.com/partigabor/"

# [[params.social]]
# name = "LinkedIn"
# icon = "fa fa-2x fa-linkedin"
# weight = 4
# url = "https://www.linkedin.com/in/ramtin-ehsani/"

#[[params.social]]
#name = "Zotero"
#icon = "fa fa-2x fa-zotero"
#weight = 5
#url = "https://www.zotero.org/partigabor"

# [[params.social]]
# name = "RSS"
# icon = "fa fa-2x fa-rss"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
pre = "<i class='fas fa-info'></i>"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Research"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Publications"
weight = 4
url = "publications/"

[[languages.en.menu.main]]
name = "Contact"
weight = 5
url = "contact/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.highlight]
style = "doom-one"

# Comments
[params.utterances]
  repo = "partigabor/partigabor.github.io" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "comment" # https://utteranc.es/#heading-issue-label
  theme = "photon-dark" # https://utteranc.es/#heading-theme

